using System.Text.Json.Serialization;

namespace GigaChatAdapter.Completions
{
    public class GigaChatUsage
    {
        /// <summary>
        /// Token quantity for input message
        /// </summary>
        [JsonPropertyName("prompt_tokens")]
        int PromptTokens {get; set;}

        /// <summary>
        /// Token quantity for output message (generated by AI)
        /// </summary>
        [JsonPropertyName("completion_tokens")]
        int CompletionTokens { get;set;}

        /// <summary>
        /// Total token quantity
        /// </summary>
        [JsonPropertyName("total_tokens")]
        int TotalTokens { get; set;}
    }
}
